Revert "Revert "Revert "Add python3 subpackage"""
This breaks anyone following TripleO documentation to setup repos. The failure is:

Error: Package: openstack-tripleo-common-9.1.1-0.20180703132149.648aa43.el7.noarch (delorean)
           Requires: python2-tripleo-common
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest



This reverts commit 35ab61b17467d25b60388149523c5ed5f51d466f.

Change-Id: I28752152d3f4af0c6eaa4ce36c710952bc9e646e